version: '3.7'
services:
  jts_db:
    container_name: jts_db
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER:-jts_db_user}
      POSTGRES_PASSWORD: ${DB_PASS:-jts_db_pass}
      POSTGRES_DB: jst_app
      PGDATA: /data/postgres
    volumes:
       - jts_db-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - jts_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 0.5G
          cpus: '0.05'

  jts_zoo:
    container_name: jts_zoo
    image: zookeeper:3.4.9
    hostname: jts_zoo
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=jts_zoo:2888:3888
    volumes:
      - jts_zoo-data:/data
      - jts_zoo-datalog:/datalog
    networks:
      - jts_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 0.5G
          cpus: '0.05'

  jts_kafka:
    container_name: jts_kafka
    image: confluentinc/cp-kafka:5.5.1
    hostname: jts_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://jts_kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "jts_zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - jts_kafka-data:/var/lib/kafka/data
    networks:
      - jts_network
    restart: unless-stopped
    depends_on:
      - jts_zoo
    deploy:
      resources:
        limits:
          memory: 0.5G
          cpus: '0.05'
  jts_git:
    container_name: jts_git
    image: jts-git-service:latest
    hostname: jts_git
    ports:
      - 2222:2222
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=false
      - USER_NAME=jts_admin
      - PUBLIC_KEY_FILE=/ssh-keys/jts_rsa.pub
    volumes:
      - jts_git-data:/repo/configuration.git
    networks:
      - jts_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 0.25G
          cpus: '0.05'
  jts_config:
    container_name: jts_config
    image: jts-config-service:latest
    hostname: jts_config
    ports:
      - 6001:8080
    environment:
      - PROFILE=devel
    networks:
      - jts_network
    restart: "no"
    depends_on:
      - jts_git
    deploy:
      resources:
        limits:
          memory: 0.5G
          cpus: '0.05'

networks:
  jts_network:
    driver: bridge

volumes:
    jts_db-data:
    jts_zoo-data:
    jts_zoo-datalog:
    jts_kafka-data:
    jts_git-data:
